### ISSUE TITLE
Ability to make changes to a device programmatically through Salt

### ISSUE THREAD

**Issue by meggiebot** [saltstack/salt#29550]
https://saltstack.zendesk.com/agent/tickets/400

- [x] system updates module (`softwareupdate`) #30311
- [x] system setup module (`systemsetup`) #30312
- [x] system module #30451 
- [x] timezone module #30398 
- [x] power module #30399
- [x] additional system module items #30400
- [x] mac service module #30440
