### ISSUE TITLE
SLEPIC: Deprecate win_update.py

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#32828]
### Description of Issue/Question

Deprecate `win_update.py` in favor of `win_wua.py`
- [x] Write state module for `win_wua.py`
- [ ] See if it's possible to use commands that work for `win_update.py` with the `win_wua.py` module
- [x] Put in deprecation warnings for the `win_update` module

**Comment by meggiebot** [comment]
This is a nice to have for Nitrogen, not a blocker.

**Comment by Ch3LL** [comment]
@twangboy is this ready to be closed?

**Comment by twangboy** [comment]
@Ch3LL I left it open because I haven't really looked at the 2nd bullet.....
