### ISSUE TITLE
2019.2.2 Release checklist 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#55009]
### Release Checklist 
- [x] Jenkins test green 
- [x] Internal testing by teams like support, PS, QA to ensure critical use cases aren't broken
- [x] Manual Testing 
- [x] Generate release Tag
 
Complete the below packages and host them in staging area
- [x] RedHat/CentOS 6 py2 (both x86_64 and i386)
- [x] RedHat/CentOS 7 py2
- [x] RedHat/CentOS 7 py3 
- [x] RedHat/CentOS 8 py3
- [x] Debian 8 py2
- [x] Debian 9 py2
- [x] Debian 9 py3
- [x] Debian 10 py3
- [x] Ubuntu 16.04 py2 
- [x] Ubuntu 16.04 py3
- [x] Ubuntu 18.04 py2
- [x] Ubuntu 18.04 py3
- [x] Windows py2
- [x] Windows py3
- [x] MacOS py2
- [x] MacOS py3
- [x] Amazon Linux 1 
- [x] Amazon Linux 2 py2
- [x] Amazon Linux 2 py3
- [x] Raspbian 8 py2
- [x] Raspbian 9 py2
- [x] Raspbian 9 py3
- [x] Raspbian 10 py3
- [x] Complete testing of the packages 
- [x] Move packages from staging to repo.saltstack.com 
- [x] Released

**Comment by dmurphy18** [comment]
@KChandrashekhar Amazon Linux 2 has Py2 (basically sy linked to RHEL 7 on the repo) and Py3.

No Raspbian 8 Py3, Fedora 29 is going away soon, Fedora 31 should be added but it has dwoz kind of Tornado v5.x Py3 support using pre-released 2019.2.1 and that needs to be addressed, was hoping Neon would be sooner. than December.  Also Fedora now uses Tornado v6.x which has stack_context removed(deprecated and now removed) hence really need a fix for that. You are missing RHEL 6 Py2 (both x86_64 and i386)

**Comment by kiemlicz** [comment]
Excuse the interruption but this is the first time I see the checklist and estimated release date of upcoming release.
I would like to comment: I like this approach very much, please it running!

**Comment by OrangeDog** [comment]
Most of the ["Fix planned in 2019.2.2 release"](https://docs.saltstack.com/en/latest/topics/releases/2019.2.1.html) issues are still open...

**Comment by dmurphy18** [comment]
All of the Linux packages Python 2 and Python 3 have been delivered to QA

**Comment by KChandrashekhar** [comment]
> Most of the ["Fix planned in 2019.2.2 release"](https://docs.saltstack.com/en/latest/topics/releases/2019.2.1.html) issues are still open...

Verified the issues are fixed and closed.

**Comment by disaster123** [comment]
I still can't find any packages of 2019.2.2 in the repo?

**Comment by OrangeDog** [comment]
@disaster123 "Move packages from staging to repo.saltstack.com" isn't ticked yet

**Comment by KChandrashekhar** [comment]
Closing this as 2019.2.2 is released now
