### ISSUE TITLE
[EPIC] Salt Needs to update the way repos are managed since apt-key is deprecated

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#59408]
**Description**
https://wiki.debian.org/DebianRepository/UseThirdParty documents the new way that Debian repos are to be managed.

This applies to Ubuntu 20.10 and Debian 11 and later I believe based on what I've read.

Basically apt-key is deprecated, gpg keys should be placed in /usr/share/keyrings/ and should be pinned specifically in the sources.list like this:

```
deb [signed-by=/usr/share/keyrings/deriv-archive-keyring.gpg] https://deriv.example.net/debian/ stable main
```
Things we need to fix are at least:

- apt-key is used all over salt states/modules
- The repos we provide need to have a binary version of the key added to them.
- The bootstrap script, and installation instructions need to be updated to use the new way.

Tasks:

- [x] https://github.com/saltstack/salt/issues/59453
- [x] https://github.com/saltstack/salt/issues/59454
- [x] https://github.com/saltstack/salt/issues/59456
- [x] https://github.com/saltstack/salt/issues/59785
- [x] https://github.com/saltstack/salt-bootstrap/issues/1532
- [x] https://github.com/saltstack/salt/issues/59786

**Comment by sagetherage** [comment]
Let's break this up into multiple issues, this can be the epic.

**Comment by heini** [comment]
Just FYI: https://discourse.ubuntu.com/t/spec-apt-deb822-sources-by-default/29333/4
