### ISSUE TITLE
[EPIC] [WEBSITE] A few saltproject.io website bugs: partial blog posts, searchability, and timestamps

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt#59561]
**Description**

I wanted a place to track several items I'm finding related to the new website functionality. These can be broken up into smaller issues/tasks.

- [ ] Blog posts don't contain general information normally found with blog posts: timestamp of post, timestamp of last updated, etc. https://github.com/saltstack/salt/issues/59759
- [ ] Blog posts, podcasts, etc. can't be searched. They can only be eyeballed when looking at each page of posts. Need more details - searching bar added or more metadata available?
- [ ] Event calendar navigation: Events are hard to navigate. There isn't an ability to download calendar file items. Add plugin for Events and likely purchase plugin addons for flat fee
- [ ] Event calendar zoom links: Zoom links appear on the home page, but not on the events page. Can be added to the theme or template or simply add the block in the event body

**Comment by TathanT** [comment]
I found today that links are broken in the "Learn Salt" section. Should I open a new issue or should it be added to this issue?

**Comment by ScriptAutomate** [comment]
> I found today that links are broken in the "Learn Salt" section. Should I open a new issue or should it be added to this issue?

Thanks for opening https://github.com/saltstack/salt/issues/59608 on this :)

**Comment by ScriptAutomate** [comment]
Information has been submitted to team managing the https://saltproject.io within their internal ticketing / project-planning. Ticket will be closed, as website feedback (specifically for https://saltproject.io website, not for the subdomains such as https://docs.saltproject.io or https://repo.saltproject.io) is requested to go through the `Contact Us` method listed on https://saltproject.io, which is:

- Send feedback, feature requests, bugs, etc. to saltproject@vmware.com
- OR reach out the @janae417 on the [Salt Community Slack](https://join.slack.com/t/saltstackcommunity/shared_invite/zt-3av8jjyf-oBQ2M0vhXOhJpNpRkPWBvg) (she is `@Janae` on there)
